# fly.toml app configuration file generated for testtayyor
# See https://fly.io/docs/reference/configuration/ for more info.

app = "testtayyor"
primary_region = "hkg"

[env]
  NODE_ENV = "production"
  PORT = "3000"

# Serverni ishga tushirish komandasi
[processes]
  app = "node server/server.js"

[http_service]
  internal_port = 3000
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

